import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { Providers } from "./providers";

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${inter.className}  h-full antialiased`}
    >
       <body className="h-full bg-neutral-50 font-sans text-neutral-900 antialiased">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
