# Generated by Django 5.2.8 on 2026-09-22 16:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chats",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(default="Untitled Chat", max_length=255)),
                ("summary", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
            ],
            options={
                "db_table": "rag_chats",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "sender",
                    models.CharField(
                        choices=[("ai", "AI Assistant"), ("user", "User")],
                        default="user",
                        max_length=5,
                    ),
                ),
                ("sources", models.JSONField(blank=True, default=list, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chats.chats",
                    ),
                ),
            ],
            options={
                "db_table": "rag_message",
                "ordering": ["created_at"],
            },
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE IF EXISTS rag_chats ADD COLUMN IF NOT EXISTS summary text DEFAULT '';
            ALTER TABLE IF EXISTS rag_message ADD COLUMN IF NOT EXISTS sources jsonb DEFAULT '[]'::jsonb;
            """,
            reverse_sql="",
        ),
    ]
