# Generated by Django 5.2.8 on 2026-09-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="retrieved_chunk_ids",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="message",
            name="trace_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
