# Generated by Django 5.2.8 on 2026-09-21 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rag", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=225)),
                (
                    "sender",
                    models.CharField(
                        choices=[("ai", "AI Assistant"), ("user", "User")],
                        default="user",
                        max_length=5,
                    ),
                ),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="rag.chats",
                    ),
                ),
            ],
        ),
    ]
